S2498/letcheber support wblgt02
wiifor/framework-zephyr pull request #16
Opened 2021-08-02 14:37 UTC by letcheber

Add support for WBLGT02 board
3 commits : 
* Modify opt3001 driver
* Add flag CONFIG_BOARD_WBLGT01 for WBLGT01 board 
* Add WBLGT02 board (dts and configuration files)

2021-08-02 18:50 UTC, NicoWii4 commented on drivers/sensor/opt3001/opt3001.c
> +/**
Attention, tu dois être basé sur le patch avec les modifs de tests pour la WBLGT01. Rebase toi sur master

2021-08-03 08:09 UTC, letcheber commented on drivers/sensor/opt3001/opt3001.c
> +/**
Done

2021-08-03 22:13 UTC, Cyril-Roques approved these changes

2021-08-09 07:09 UTC, NicoWii4 requested changes

2021-08-09 07:09 UTC, NicoWii4 commented on boards/arm/WBLGT02/WBLGT02.dts
> +		status = "reserved";
Ce champ là n'est plus necessaire pour la WBLGT01 (ou faut changer en okay)

2021-08-09 09:05 UTC, letcheber commented on boards/arm/WBLGT02/WBLGT02.dts
> +		status = "reserved";
Done

2021-08-09 12:15 UTC, NicoWii4 approved these changes

2021-08-09 13:09 UTC, merged