s2321 - update linker file to flash FS
wiifor/framework-zephyr pull request #3
Opened 2021-04-16 14:12 UTC by letcheber

Change-Id: Iac5713c8d47308cad13b7fbbae0d76fdb0c1a10d
Signed-off-by: Lisa Etcheber <lisa.etcheber@wiifor.com>

2021-04-16 14:18 UTC, letcheber commented
Ajout d'une section "FLASH FS" dans la mémoire
Ajout du lien vers la création du binaire associé littlefsbin.bin

2021-04-19 20:37 UTC, ltawii commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +    FLASH_FS 		      (rwx) : ORIGIN = (ROM_ADDR + ROM_SIZE), LENGTH = 32K
On aurait dû introduire un flag CONFIG_FLASH_FS non ?

2021-04-19 20:37 UTC, ltawii commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +    IDT_LIST              (wx) : ORIGIN = (RAM_ADDR + RAM_SIZE), LENGTH = 2K
Je ne vois pas de changement ?

2021-04-19 20:37 UTC, ltawii commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +
?

2021-04-20 08:39 UTC, letcheber commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +    IDT_LIST              (wx) : ORIGIN = (RAM_ADDR + RAM_SIZE), LENGTH = 2K
en effet, c'est uniquement pour que les infos de MEMORY{...} soient alignées mais pas de changement de données

2021-04-20 09:01 UTC, Cyril-Roques commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +    FLASH_FS 		      (rwx) : ORIGIN = (ROM_ADDR + ROM_SIZE), LENGTH = 32K
je pense aussi qu'il faut faire des defines, sinon on va casser la compil si on l'utilise sur un autre plateforme

2021-04-20 09:03 UTC, letcheber commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +    FLASH_FS 		      (rwx) : ORIGIN = (ROM_ADDR + ROM_SIZE), LENGTH = 32K
je fais ça

2021-04-20 09:05 UTC, Cyril-Roques requested changes

2021-04-20 09:05 UTC, Cyril-Roques commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +	32K)
tu peux faire un define pour la taille du filesystem ce sera plus facile à lire plus tard

2021-04-20 09:05 UTC, Cyril-Roques commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +
tu peux supprimer cette modif

2021-04-20 09:05 UTC, Cyril-Roques commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +    IDT_LIST              (wx) : ORIGIN = (RAM_ADDR + RAM_SIZE), LENGTH = 2K
vu que l'on est sur un repo qui ne nous appartient pas, essaye au maximum de limiter les changements, ça évitera les problèmes de rebase futurs

2021-04-20 09:06 UTC, letcheber commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +    IDT_LIST              (wx) : ORIGIN = (RAM_ADDR + RAM_SIZE), LENGTH = 2K
ok

2021-04-20 12:55 UTC, letcheber commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +
Saut de ligne supprimé

2021-04-20 12:55 UTC, letcheber commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +	32K)
fait

2021-04-22 06:10 UTC, vinceWii4 approved these changes

2021-04-22 07:37 UTC, Cyril-Roques requested changes

2021-04-22 07:37 UTC, Cyril-Roques commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +#define CONFIG_FLASH_FS
ce flag devrait plutôt être dans platformio.ini ou dans prj.conf

2021-04-22 07:37 UTC, Cyril-Roques commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +#define ROM_SIZE (CONFIG_FLASH_SIZE*1K - CONFIG_FLASH_LOAD_OFFSET - \
#ifdef CONFIG_FLASH_FS
#define ROM_SIZE (CONFIG_FLASH_SIZE*1K - CONFIG_FLASH_LOAD_OFFSET - FLASH_FS_SIZE)
#else
#define ROM_SIZE (CONFIG_FLASH_SIZE*1K - CONFIG_FLASH_LOAD_OFFSET)
#endif

2021-04-22 07:37 UTC, Cyril-Roques commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +TARGET(binary) /* specify the file format of binary file */
pareil ici à mettre sous flag CONFIG_FLASH_FS

2021-04-22 07:37 UTC, Cyril-Roques commented on include/arch/arm/aarch32/cortex_m/scripts/linker.ld
> +SECTION_PROLOGUE(.flash_fs,,)
pareil ici

2021-04-22 16:18 UTC, Cyril-Roques approved these changes

2021-04-22 18:20 UTC, merged