Add hibernate enable function using dts configuration
wiifor/framework-zephyr pull request #7
Opened 2021-05-10 12:51 UTC by NicoWii4

Change-Id: Ie17684f242e9fff0017f1c3751ec389c24b999a1
Signed-off-by: Nicolas <nicolas.pelissier@wiifor.com>

2021-05-11 22:46 UTC, Cyril-Roques requested changes
extend commits messages to add goal informations, breaking changes ...

2021-05-11 22:46 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.c
> +#include <drivers/sensor/max1726x.h>
add a blank line after

2021-05-11 22:46 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.c
> +			      int16_t val)
this change should not be here

2021-05-11 22:46 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.c
> +	uint8_t i2c_data[3] = { reg_addr, val & 0xFF, (uint16_t)val >> 8 };
revert this changes

2021-05-11 22:46 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.c
> +	return i2c_write(cfg->i2c, i2c_data, sizeof(i2c_data), cfg->i2c_addr);
revert here too

2021-05-11 22:46 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
> +			   MAX1726X_EN_HIB | MAX1726X_HIB_ENTER_TIME(config->hib_enter_time) |
align indentation like other functions

2021-05-11 22:46 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.c
> +	max1726x_reg_write(dev, VEMPTY,
revert this reformat

2021-05-11 22:46 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.c
> +	static struct max1726x_data max1726x_data_##n;                         \
revert reformat

2021-05-11 22:46 UTC, taptada commented on drivers/sensor/max1726x/max1726x.h
> +#define VOLTAGE_MULTIPLIER_UV 1250 / 16
c'est bizarre ces changements, fin de ligne ?

2021-05-11 22:46 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.h
> +enum { STATUS = 0x00,
revert reformating

2021-05-11 22:46 UTC, taptada commented on dts/bindings/sensor/maxim,max1726x.yaml
> +# Copyright 2020 Matija Tudan
faut faire un git mv plutôt qu'un simple mv sinon on perd l'historique

2021-05-11 22:46 UTC, taptada commented on samples/sensor/max1726x/README.rst
> +data from the MAX1726X device that implements SENSOR_CHAN_GAUGE_VOLTAGE,
je pense qu'il faut passer au pluriel ici

2021-05-11 22:46 UTC, taptada commented on samples/sensor/max1726x/README.rst
> +.. _max1726x datasheet: https://datasheets.maximintegrated.com/en/ds/MAX1726X.pdf
lien mort

2021-05-12 14:20 UTC, NicoWii4 commented on drivers/sensor/max1726x/max1726x.h
> +#define VOLTAGE_MULTIPLIER_UV 1250 / 16
Oui, je sais pas pourquoi...

2021-05-12 14:36 UTC, NicoWii4 commented on dts/bindings/sensor/maxim,max1726x.yaml
> +# Copyright 2020 Matija Tudan
Je comprends pas, l'historique devrais être visible maintenant non ?

2021-05-12 14:37 UTC, NicoWii4 commented on samples/sensor/max1726x/README.rst
> +data from the MAX1726X device that implements SENSOR_CHAN_GAUGE_VOLTAGE,
Effectivement, je modifie ça sur le premier patch

2021-05-19 16:01 UTC, closed without merging

2021-05-19 16:01 UTC, NicoWii4 commented
Doing an unik pull request