Add max1726x shutdown enable function
wiifor/framework-zephyr pull request #8
Opened 2021-05-12 14:18 UTC by NicoWii4

2021-05-18 16:14 UTC, Cyril-Roques requested changes

2021-05-18 16:14 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.c
> +static int max1726x_set_shutdown(const struct device *dev)
max1726x_shutdown ou max1726x_pwr_shutdown plutôt

2021-05-18 16:14 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.h
> +#define MAX1726X_SHDN (BIT(7))
MAX1726X_EN_SHDN

2021-05-18 16:14 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.h
> +	   CONFIG = 0x1D,
le registre ne s'appelle que config ?

2021-05-19 16:01 UTC, closed without merging

2021-05-19 16:02 UTC, NicoWii4 commented
Doing an unik pull request