Add max17260 support
wiifor/framework-zephyr pull request #9
Opened 2021-05-12 16:11 UTC by NicoWii4

Signed-off-by: Nicolas <nicolas.pelissier@wiifor.com>

2021-05-18 16:04 UTC, Cyril-Roques requested changes

2021-05-18 16:04 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
> +static int capacity_to_ma(unsigned int rsense_mohms, int16_t val)
ma -> mah ? 
je pense que la capacité doit être en milliampère heure (à modifier dans la description aussi

2021-05-18 16:04 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
> +	float lsb_units;
il faut éviter les floats dans le kernel

2021-05-18 16:04 UTC, Cyril-Roques commented on dts/bindings/sensor/maxim,max1726x.yaml
> +    rsense-mohms:
faut pas ajouter ça dans les tests aussi ?

2021-05-21 06:48 UTC, Cyril-Roques approved these changes

2021-05-21 07:03 UTC, Cyril-Roques requested changes

2021-05-21 07:03 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
> +<<<<<<< s2580_hibernate
supprimer ça

2021-05-21 07:03 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
> +	rc = i2c_burst_read(cfg->i2c, cfg->i2c_addr, reg_addr, i2c_data, 2);
à remttre comme avant

2021-05-21 07:03 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
> +			      int16_t val)
à remttre comme avant

2021-05-21 07:03 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
> +	uint8_t i2c_data[3] = { reg_addr, val & 0xFF, (uint16_t)val >> 8 };
à remttre comme avant

2021-05-21 07:03 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
> +	return i2c_write(cfg->i2c, i2c_data, sizeof(i2c_data), cfg->i2c_addr);
à remttre comme avant

2021-05-21 07:03 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
> +static int max1726x_config(const struct device *dev, enum sensor_channel chan,
manque la description

2021-05-21 07:03 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
> +static int max1726x_attr_set(const struct device *dev, enum sensor_channel chan,
manque la description

2021-05-21 07:03 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
> +		LOG_ERR("Could not get pointer to %s device",
à remettre comme avant

2021-05-21 07:03 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
> +#define MAX1726X_INIT(n)                                                       \
il faut garder les \ aligné

2021-05-21 07:03 UTC, taptada commented on drivers/sensor/max1726x/max1726x.h
> +enum { STATUS = 0x00,
à remettre comme avant

2021-05-21 07:03 UTC, taptada commented on drivers/sensor/max1726x/max1726x.h
> +enum { FSTAT_DNR = 0x01,
à remettre comme avant

2021-05-21 07:03 UTC, taptada commented on drivers/sensor/max1726x/max1726x.h
> +	/* Exit Time (s) = (hibernate_exit_time+1)x702msx2^(hibernate_scalar) */
est-ce que ces description bien détaillée n'irait pas plutôt dans le yaml ?

2021-05-21 07:03 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
> -<<<<<<< s2580_hibernate
à supprimer

2021-05-21 07:03 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
> +/**
à mettre dans le commit précédent

2021-05-21 07:03 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
> -static int max1726x_set_hibernate(const struct device *dev)
elle était définie 2 fois cette fonction ?

2021-05-21 07:03 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.h
> +	   CONFIG = 0x1D,
à aligner

2021-05-21 07:03 UTC, Cyril-Roques commented on drivers/sensor/max17055/max17055.c
> +		tmp = capacity_to_mah(config->rsense_mohms, priv->design_cap);
c'est à renommer dans un patch précedent non ?

2021-05-25 07:14 UTC, Cyril-Roques requested changes

2021-05-25 07:14 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.c
> + * @param val The value of the chan
channel

2021-05-25 07:14 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.c
> + * @param val The value of the chan
channel

2021-05-25 07:14 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.c
> +#define MAX1726X_INIT(n)                                                       \
plus qu'un ;)

2021-05-25 07:14 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.h
> +#define TIME_MULTIPLIER_MS 5625
pas de raison de modifier l'alignement

2021-05-25 07:14 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.h
> +#define MAX1726X_HIB_ENTER_TIME_MASK (0x07)
le coding style implique que les define soient aligner donc il faut le faire là où tu en définis

2021-05-25 07:14 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.h
> +	CONFIG 			= 0x1D,
il faut les aligner comme les autres

2021-05-25 07:14 UTC, Cyril-Roques commented on drivers/sensor/max1726x/max1726x.c
>  		     cfg->i2c_addr);
le commit message est à reprendre (add max260 support)

2021-05-26 14:46 UTC, ltawii reviewed
Il est bizarre le nom du commit : shutdown enable function
Pkoi pas shutdown function ?

2021-05-26 16:54 UTC, taptada commented on drivers/sensor/max1726x/max1726x.c
>  		     cfg->i2c_addr);
il faut virer le changeid

2021-05-28 15:32 UTC, Cyril-Roques reviewed
+1

2021-05-28 15:33 UTC, Cyril-Roques approved these changes

2021-06-14 23:22 UTC, merged